timeout: 1200s
substitutions:
  _CUSTOM_REGION: europe-west3
  _CUSTOM_CLUSTER: gke-cluster
steps:
  # Configure a kubectl workspace for this project
  - name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config

  # Deploy with Helm
  - name: gcr.io/$PROJECT_ID/helm
    args:
      - upgrade
      - -i
      - go-nihao
      - ./go-nihao-chart
      - --set
      - image.repository=gcr.io/$PROJECT_ID/go-nihao,image.tag=$COMMIT_SHA
      - -f
      - ./kubernetes/values.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true
