timeout: 1200s
substitutions:
  _CUSTOM_REGION: europe-west3-a
  _CUSTOM_CLUSTER: cluster-1
steps:
  - name: gcr.io/cloud-builders/kubectl
    id: Configure kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config

  - name: gcr.io/$PROJECT_ID/helm
    id: Deploy chart
    args:
      - upgrade
      - -i
      - go-nihao
      - ./go-nihao-chart
      - --set
      - image.repository=gcr.io/$PROJECT_ID/go-nihao, image.tag=5455ae4c04cbdf0c8c994296634eafd2bc227a5c
      - -f
      - ./go-nihao-chart/values.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true
